# Generated by Django 5.1.7 on 2025-04-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='grupo',
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='situacion',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, verbose_name='Situación'),
        ),
    ]
