# Generated by Django 5.1.7 on 2025-04-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_estudiantes', '0004_alter_nota_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
