# Generated by Django 5.1.7 on 2025-04-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_estudiantes', '0005_alter_estudiante_fecha_registro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nota',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Nota', 'verbose_name_plural': 'Notas'},
        ),
        migrations.AlterField(
            model_name='nota',
            name='fecha_registro',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
